import React from "react";
import { Flex, Button } from "@chakra-ui/react";
import Link from "next/link";
import Head from "next/head";

const NotFound: React.FC = () => {
  return (
    <div>
      <Head>
        <title>오류</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/not-found-512.webp" />
      </Head>
      <Flex
        direction="column"
        justifyContent="center"
        alignItems="center"
        minHeight="60vh"
      >
        죄송합니다. 해당 기능은 준비 중입니다.
        <Link href="/">
          <Button mt={4}>돌아가기</Button>
        </Link>
      </Flex>
    </div>
  );
};
export default NotFound;
